name: psalm

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  psalm:
    name: Psalm Static Analysis on PHP ${{ matrix.php-version }} (Ubuntu 24.04)
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        php-version:
          - '8.2'
          - '8.3'
          - '8.4'
    steps:
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, xml

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --dev

      - name: Run Psalm
        run: vendor/bin/psalm --config=psalm.xml.dist --show-info=true
